name: Pack Solution

on:
  push:
    paths:
      - contents/**
  workflow_dispatch:

jobs:
  build:
    name: Build Solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.2.0

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1.2.0
        with:
          solution-file: out/contoso_university_core.zip
          solution-folder: contents
          solution-type: Both

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: packed-solution
          path: out/
