name: Pack Contoso_university_core

on:
  push:
    paths:
    - contents/**
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/actions-install@v1.2.0
      - uses: microsoft/powerplatform-actions/pack-solution@v1.2.0
        with:
          solution-file: contoso_university_core.zip
          solution-folder: contents
          solution-type: Both
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: packed-solution
          path: out/

      
